environment:
  matrix:
  - nodejs_version: "10"
    platform: x64
  - nodejs_version: "10"
    platform: x86
  - nodejs_version: "11"
    platform: x64
  - nodejs_version: "11"
    platform: x86
  - nodejs_version: "12"
    platform: x64
  - nodejs_version: "12"
    platform: x86
  - nodejs_version: "13"
    platform: x64
  - nodejs_version: "13"
    platform: x86
  - nodejs_version: "14"
    platform: x64
  - nodejs_version: "14"
    platform: x86

install:
  - where npm
  - where node
  - ps: Install-Product node $env:nodejs_version $env:platform
  - 'npm install -g npm@latest prebuildify node-gyp'

build: off

artifacts:
  - path: './bcrypt*.tgz'

test_script:
  - node --version
  - npm --version
  - npm install --build-from-source
  - npm test

after_test:
  - npm run build
  - npm run pack

on_success:
  - ps: >
        if ($env:NODE_PRE_GYP_GITHUB_TOKEN -ne $null -and $env:APPVEYOR_REPO_TAG_NAME -match '^v(0|[1-9]+)\.(0|[1-9]+)\.(0|[1-9]+)(-\w)?$') {
            echo "Publishing $env:APPVEYOR_REPO_TAG_NAME"
            ## TODO CONFIGURE FOR GITHUB NPM REGISTRY ###
            ## See https://docs.github.com/en/actions/guides/publishing-nodejs-packages#publishing-packages-to-github-packages
            npm publish
        }

